### ISSUE TITLE
后端接口209异常

### ISSUE THREAD

**Issue by WAMiii** [dgiot/dgiot_deploy#3]
![image](https://user-images.githubusercontent.com/49750324/113104384-0e8c5f80-9233-11eb-8035-10f8c9fda8d0.png)
![image](https://user-images.githubusercontent.com/49750324/113104398-14824080-9233-11eb-8a34-33e37b3b6e41.png)
![image](https://user-images.githubusercontent.com/49750324/113105153-d9ccd800-9233-11eb-82b9-104750281ff9.png)

**Comment by h7ml** [comment]
改问题已修复，请重新克隆[dgiot_dashboard](https://github.com/dgiot/dgiot_dashboard/)
